Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace GoldDuck.Models
{
    public class LoginViewModel : BaseEntity
    {
        [Required]
        public string email {get; set;}

        [Required]
        [DataType(DataType.Password)]
        public string password {get; set;}

    }
}

Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
namespace GoldDuck.Models
{
    public class RegisterViewModel : BaseEntity
    {
        [Required]
        [MinLength(2)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string firstName { get; set; }

        [Required]
        [MinLength(2)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string lastName { get; set; }

        [Required]
        [EmailAddress]
        public string email { get; set; }

        [Required]
        public string alias {get; set;}

        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MinLength(8)]
        public string password {get; set;}

        [Required(ErrorMessage = "Confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage="Password confirmation and password do not match.")]
        public string passwordConfirmation {get; set;}

    }

}

Controllers/LogRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GoldDuck.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace GoldDuck.Controllers
{
    public class LogRegController : Controller
    {
        private GoldDuckContext _context;
        public LogRegController(GoldDuckContext context)
        {
            _context = context;
        }
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {

            if (HttpContext.Session.GetInt32("user_id") != null)
            {
                return RedirectToAction("bright_ideas", "Main");
            }
            return View();
        }

        [HttpPost]
        [Route("Register")]

        public IActionResult Register(RegisterViewModel model)
        {
            List<User> existingAliases = _context.users.Where(item => item.alias == model.alias).ToList();
            List<User> existingEmails = _context.users.Where(item => item.email == model.email).ToList();
            if (existingAliases.Count > 0)
            {
                TempData["aliasError"] = "A user with that alias already exists";
                return RedirectToAction("Index");
            }
            if (existingEmails.Count > 0)
            {
                TempData["emailError"] = "A user with that email already exists";
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                User user = new User
                {
                    firstName = model.firstName,
                    lastName = model.lastName,
                    email = model.email,
                    alias = model.alias,
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now,
                    password = ""
                };
                user.password = Hasher.HashPassword(user, model.password);
                _context.users.Add(user);
                _context.SaveChanges();

                
                User addedUser = _context.users.SingleOrDefault(item => item.email == model.email);
                HttpContext.Session.SetInt32("user_id", addedUser.id);
                return RedirectToAction("bright_ideas", "Main");
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        [Route("Login")]

        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                List<User> users = _context.users.Where(item => item.email == model.email).ToList();
                if (users.Count < 1)
                {
                    TempData["loginError"] = "No user with that email found";
                    return RedirectToAction("Index");
                }
                User user = users[0];
                var Hasher = new PasswordHasher<User>();
                if (Hasher.VerifyHashedPassword(user, user.password, model.password) != 0)
                {
                    HttpContext.Session.SetInt32("user_id", user.id);
                    return RedirectToAction("bright_ideas", "Main");
                }
                else
                {
                    TempData["loginError"] = "That password does not match what is on record";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(model);
            }
        }

        
    }
}

Views/LogReg/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bank Accounts</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                @Html.Partial("Login")
            </div>
            <div class="col-md-6">
                @Html.Partial("Register")
            </div>
        </div>
    </div>
</body>
</html>

Views/LogReg/Login.cshtml
@model GoldDuck.Models.LoginViewModel

<h2>Login</h2>
@{
    if (TempData["loginError"] != null)
    {
        <p>@TempData["loginError"]</p>
    }
}
<form asp-controller="LogReg" asp-action="Login" method="POST">  
    <span asp-validation-for="email"></span>
    <label asp-for="email">Email:</label>
    <input asp-for="email" class="form-control"/>  
    <span asp-validation-for="password"></span>
    <label asp-for="password">Password:</label>
    <input asp-for="password" class="form-control"/>
    <input type="submit" value="Login" class="btn-primary">
</form>

Views/LogReg/Register.cshtml
@model GoldDuck.Models.RegisterViewModel

<h2>Registration</h2>
@{
    @if (TempData["aliasError"] != null)
    {
        <p>@TempData["aliasError"]</p>
    }
    @if (TempData["emailError"] != null)
    {
        <p>@TempData["emailError"]</p>
    }
}
<form asp-controller="LogReg" asp-action="Register" method="POST">
    <span asp-validation-for="firstName"></span>
    <label asp-for="firstName">First Name:</label>
    <input asp-for="firstName" class="form-control"/>
    <span asp-validation-for="lastName"></span>
    <label asp-for="lastName">Last Name:</label>
    <input asp-for="lastName" class="form-control"/>
    <span asp-validation-for="email"></span>
    <label asp-for="email">Email:</label>
    <input asp-for="email" class="form-control"/>
    <span asp-validation-for="alias"></span>
    <label asp-for="alias">Alias: </label>
    <input asp-for="alias" class="form-control"/>
    <span asp-validation-for="password"></span>
    <label asp-for="password">Password:</label>
    <input asp-for="password" class="form-control"/>
    <span asp-validation-for="passwordConfirmation"></span>
    <label asp-for="passwordConfirmation">Confirm Password:</label>
    <input asp-for="passwordConfirmation" class="form-control"/>
    <input type="submit" value="Register" class="btn-primary">
</form>